version: '3.2'
services:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
    - 3000:3000
    depends_on: 
    - prometheus
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
  #   - node_exporter

  # node_exporter:
  #   image: prom/node-exporter
  #   container_name: node_exporter
  #   command:
  #     - '--path.rootfs=/host'
  #   network_mode: host
  #   pid: host
  #   restart: unless-stopped
  #   volumes:
  #     - '/:/host:ro,rslave'


  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  #   depends_on:
  #   - redis

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #   - 6379:6379