global:
  scrape_interval: 15s


scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node
  static_configs:
  - targets: ['192.168.43.178:9182']