global:
  scrape_interval: 5s


scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: node
  static_configs:
  - targets: ['172.17.211.8:9100', '172.29.121.59:9100']
  basic_auth:
      username: prometheus
      password: xxx